defaults: &defaults
  locations_url: https://bibdata.princeton.edu/locations/digital_locations.json
  derivative_path: <%= Rails.root.join("tmp", "derivatives") %>
  repository_path: <%= Rails.root.join("tmp", "files") %>
  cantaloupe_url: <%= ENV.fetch('CANTALOUPE_URL', 'http://localhost:8182/iiif/2/') %>
  jp2_recipes:
    default_color: >
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 
      -jp2_space sRGB 
      -double_buffering 10 
      -num_threads 1 
      -no_weights 
      Clevels=6 
      Clayers=8 
      Cblk=\{64,64\} 
      Cuse_sop=yes 
      Cuse_eph=yes  
      Corder=RPCL 
      ORGgen_plt=yes 
      ORGtparts=R 
      Stiles=\{1024,1024\}
    default_gray: >
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 
      -jp2_space sLUM 
      -double_buffering 10 
      -num_threads 1
      -no_weights 
      Clevels=6 
      Clayers=8 
      Cblk=\{64,64\} 
      Cuse_sop=yes 
      Cuse_eph=yes  
      Corder=RPCL 
      ORGgen_plt=yes 
      ORGtparts=R 
      Stiles=\{1024,1024\}
    geo_color: >
      -no_palette
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 
      -jp2_space sRGB 
      -double_buffering 10 
      -num_threads 1 
      -no_weights 
      Clevels=6 
      Clayers=8 
      Cblk=\{64,64\} 
      Cuse_sop=yes 
      Cuse_eph=yes  
      Corder=RPCL 
      ORGgen_plt=yes 
      ORGtparts=R 
      Stiles=\{1024,1024\}
    geo_gray: >
      -no_palette
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 
      -jp2_space sLUM 
      -double_buffering 10 
      -num_threads 1
      -no_weights 
      Clevels=6 
      Clayers=8 
      Cblk=\{64,64\} 
      Cuse_sop=yes 
      Cuse_eph=yes  
      Corder=RPCL 
      ORGgen_plt=yes 
      ORGtparts=R 
      Stiles=\{1024,1024\}

development:
  <<: *defaults
  repository_path: <%= Rails.root.join("tmp", "more_files") %>

test:
  <<: *defaults

production:
  <<: *defaults
  repository_path: "/opt/repository/files"
  derivative_path: "/opt/repository/derivatives"

staging:
  <<: *defaults
  repository_path: "/opt/repository/files"
  derivative_path: "/opt/repository/derivatives"
