development:
  host: localhost
  port: 6379
test:
  host: localhost
  port: 6379
production: &production
  host: <%= ENV['FIGGY_REDIS_URL'] || 'localhost' %>
  port: <%= ENV['FIGGY_REDIS_PORT'] || '6379' %>
  db: <%= ENV['FIGGY_REDIS_DB'] || 0 %>
staging:
  <<: *production
